on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'before printing job cintents'
        run: ls

      - name: 'Testing printing'
        run: echo omar

      - uses: actions/checkout@v3

      - name: 'after printing job cintents'
        run: ls
      
      - name: "login to Dockerhub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME }}  --password ${{ secrets.DOCKER_USERNAME }}  

      - name: 'Building docker image'
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/test1 .

      - name: "pushing to Dockerhub"
        run: docker push ${{ secrets.DOCKER_USERNAME }}/test1

