on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'before printing job cintents'
        run: ls

      - name: 'Testing printing'
        run: echo omar

      - uses: actions/checkout@v3

      - name: 'after printing job cintents'
        run: ls

