on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Testin Github action'
      run: pwd

      - name: 'Testin printing'
      run: echo omar

